name: Demo Workflow

on: push  # Runs on push events

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a sample
        run: echo "Hello World" > output.txt  # Creates a sample file

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact  # Artifact name
          path: output.txt       # Upload only the output.txt file

  deploy:
    needs: build  # Ensures 'deploy' runs only if 'build' succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./  # Downloads artifact to the current directory

      - name: Display File Content
        run: cat output.txt  # Prints the file to verify
